-- Hotbill 모듈 테스트 데이터베이스 스키마 (H2)

DROP TABLE IF EXISTS TB_HOTBILL_STATUS;
DROP TABLE IF EXISTS TB_CHARGE_DATA;
DROP TABLE IF EXISTS TB_HOTBILL_BILLING_INFO;
DROP TABLE IF EXISTS TB_BILLING_INFO;
DROP TABLE IF EXISTS TB_POSTING_HISTORY;
DROP TABLE IF EXISTS TB_CANCELLATION_LOG;
DROP TABLE IF EXISTS TB_CONTRACT;
DROP TABLE IF EXISTS TB_SERVICE;

-- 1. 핫빌 진행상태 테이블
CREATE TABLE TB_HOTBILL_STATUS (
    CONTRACT_NUMBER     VARCHAR(20)     NOT NULL,
    HOTBILL_DATE        DATE            NOT NULL,
    USECASE             VARCHAR(20)     NOT NULL,
    STATUS              VARCHAR(20)     NOT NULL,
    REQUEST_DATETIME    TIMESTAMP       NOT NULL,
    UPDATE_DATETIME     TIMESTAMP       NOT NULL,
    ERROR_MESSAGE       VARCHAR(500),
    CONSTRAINT PK_HOTBILL_STATUS PRIMARY KEY (CONTRACT_NUMBER, HOTBILL_DATE)
);

-- 2. 과금자료 테이블
CREATE TABLE TB_CHARGE_DATA (
    CONTRACT_NUMBER     VARCHAR(20)     NOT NULL,
    HOTBILL_DATE        DATE            NOT NULL,
    CHARGE_CODE         VARCHAR(20)     NOT NULL,
    AMOUNT              DECIMAL(15,2)   NOT NULL,
    ERROR_CODE          VARCHAR(20),
    ERROR_MESSAGE       VARCHAR(500),
    CREATE_DATETIME     TIMESTAMP       NOT NULL,
    CONSTRAINT PK_CHARGE_DATA PRIMARY KEY (CONTRACT_NUMBER, HOTBILL_DATE, CHARGE_CODE)
);

-- 3. 핫빌청구정보 테이블
CREATE TABLE TB_HOTBILL_BILLING_INFO (
    CONTRACT_NUMBER     VARCHAR(20)     NOT NULL,
    HOTBILL_DATE        DATE            NOT NULL,
    SEQ_NO              INT             NOT NULL,
    CHARGE_CODE         VARCHAR(20)     NOT NULL,
    AMOUNT              DECIMAL(15,2)   NOT NULL,
    SETTLEMENT_YN       CHAR(1)         DEFAULT 'N',
    CREATE_DATETIME     TIMESTAMP       NOT NULL,
    UPDATE_DATETIME     TIMESTAMP       NOT NULL,
    CONSTRAINT PK_HOTBILL_BILLING_INFO PRIMARY KEY (CONTRACT_NUMBER, HOTBILL_DATE, SEQ_NO)
);

-- 4. 청구정보 테이블
CREATE TABLE TB_BILLING_INFO (
    CONTRACT_NUMBER     VARCHAR(20)     NOT NULL,
    BILLING_MONTH       CHAR(6)         NOT NULL,
    SEQ_NO              INT             NOT NULL,
    CHARGE_CODE         VARCHAR(20)     NOT NULL,
    AMOUNT              DECIMAL(15,2)   NOT NULL,
    HOTBILL_YN          CHAR(1)         DEFAULT 'N',
    CREATE_DATETIME     TIMESTAMP       NOT NULL,
    CONSTRAINT PK_BILLING_INFO PRIMARY KEY (CONTRACT_NUMBER, BILLING_MONTH, SEQ_NO)
);

-- 5. 포스팅이력 테이블
CREATE TABLE TB_POSTING_HISTORY (
    CONTRACT_NUMBER     VARCHAR(20)     NOT NULL,
    HOTBILL_DATE        DATE            NOT NULL,
    SEQ_NO              INT             NOT NULL,
    POSTING_DATA        CLOB            NOT NULL,
    CREATE_DATETIME     TIMESTAMP       NOT NULL,
    CONSTRAINT PK_POSTING_HISTORY PRIMARY KEY (CONTRACT_NUMBER, HOTBILL_DATE, SEQ_NO)
);

-- 6. 핫빌취소로그 테이블
CREATE TABLE TB_CANCELLATION_LOG (
    CONTRACT_NUMBER     VARCHAR(20)     NOT NULL,
    HOTBILL_DATE        DATE            NOT NULL,
    SEQ_NO              INT             NOT NULL,
    TABLE_NAME          VARCHAR(50)     NOT NULL,
    SNAPSHOT_DATA       CLOB            NOT NULL,
    CREATE_DATETIME     TIMESTAMP       NOT NULL,
    CONSTRAINT PK_CANCELLATION_LOG PRIMARY KEY (CONTRACT_NUMBER, HOTBILL_DATE, SEQ_NO)
);

-- 테스트용 업무 테이블
CREATE TABLE TB_CONTRACT (
    CONTRACT_NUMBER     VARCHAR(20)     NOT NULL,
    TERMINATION_DATE    TIMESTAMP,
    TERMINATION_YN      CHAR(1)         DEFAULT 'N',
    CONSTRAINT PK_CONTRACT PRIMARY KEY (CONTRACT_NUMBER)
);

CREATE TABLE TB_SERVICE (
    CONTRACT_NUMBER     VARCHAR(20)     NOT NULL,
    SERVICE_CODE        VARCHAR(20)     NOT NULL,
    END_DATE            TIMESTAMP,
    CONSTRAINT PK_SERVICE PRIMARY KEY (CONTRACT_NUMBER, SERVICE_CODE)
);
